spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo-security?charset=utf8
    username: root
    password: passwd
  jpa:
    show-sql: true
server:
  port: 8888
debug: true